language: cpp


jobs:
  include:
  - stage: "Builds"
    name: "Ubuntu Build"
    os: linux
    dist: xenial
    addons:
        apt:
            packages:
                clang-6.0
                clang-format-6.0
                clang-tidy-6.0
    compiler: clang++-6.0
    before_install:
      - sudo apt-get install autoconf automake libtool curl make g++ unzip
    install:
      - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.zip
      - unzip protobuf-cpp-3.6.1.zip
      - pushd protobuf-3.6.1 && ./configure --prefix=/usr CC=gcc CXX=g++ && make && sudo make install && popd 
      - CUDA_REPO_PKG=cuda-repo-ubuntu1604_10.0.130-1_amd64.deb
      - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/$CUDA_REPO_PKG
      - sudo dpkg -i $CUDA_REPO_PKG
      - sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
      - rm $CUDA_REPO_PKG
      - sudo apt-get -y update
      - sudo apt-get install -y cuda
      - git submodule update --init --recursive
    script: 
      - cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -D CMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -D CMAKE_CXX_COMPILER=clang++ .
      - make -j4

  - stage: "Check Style"
    name: "Check clang-format"
    os: linux
    addons:
        apt:
            packages:
                clang-6.0
                clang-format-6.0
                clang-tidy-6.0
    dist: xenial
    compiler: clang++-6.0
    script:
      - bash check_format.sh clang-format-6.0


notifications:
    email:
        on_success: never
