# Configuration for scamp worker deployment
# You must apply service.yaml before creating a worker deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scamp-client
spec:
  # By default creates 3 worker pods, change as needed
  replicas: 3
  selector:
    matchLabels:
      run: scamp-client
  template:
    metadata:
      labels:
        run: scamp-client
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        # Prefer to run on preemptible nodes
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: cloud.google.com/gke-preemptible
                  operator: Exists
              weight: 100
        # Do not run on a node which is already running a pod
        # SCAMP pods will automatically utilize all available CPUs or GPUs
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: run
                operator: In
                values: 
                - scamp-client
                - scamp-server
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: client
        # Public repository which contains the docker image for the SCAMP master branch
        image: zpzim/scamp:latest
        # Run the worker on startup
        command: ["/SCAMP/build/kubernetes/SCAMPclient"]
        ports:
        - containerPort: 30078
